### ISSUE TITLE
[route] summary, 알람 모달

### ISSUE THREAD

**Issue by eun0leee** [makchamakers/makchata#7]
## 한눈에보기
- [x] 마크업/스타일링
- 지도 api
  - [x] 지도보여주기
  - [x] 지도 이동 모션
  - [x] 확대축소 기능
  - [x] 출발도착지 각각에 마커 표시
  - [x] 출발도착지 모두가 보이도록, 지도범위 재설정하기

## 알람 모달
- [x] 마크업/스타일링
- [x] 체크박스 스타일링
- [x] dim 처리
- [x] 알림적용하기 버튼 클릭시, recoil-persist 값 변경
    - [x] 알람 persist 값 직관적으로 {  text : '막차 탑승하기 1시간 전', checked : true } 로 변경

**Comment by sunaerocket** [comment]
👍
