### ISSUE TITLE
[search, route] 배포사이트 런타임에러

### ISSUE THREAD

**Issue by eun0leee** [makchamakers/makchata#72]
## 문제상황1
- search 페이지에서 빌드 에러와 husky 에러 없었으나, 배포 후 브라우저 런타임 에러 발생
  - 아래 사진은 `https://makchata.vercel.app/search` 에서 발생한 것
  - 현재 main pull 받고, 로컬에서 동작시켰을 때는 이상 없음

![Nov-22-2023 22-32-30](https://github.com/makchamakers/makchata/assets/90189513/07445d15-a4c5-4e7b-91c7-1ffd49dcb04e)

## 문제상황2
- route 페이지에서 api 조회 안됨

![스크린샷 2023-11-22 오후 10 50 54](https://github.com/makchamakers/makchata/assets/90189513/78c57bfa-8364-445d-81bd-9ae4f15b0db9)

## 해야할 것
- [ ] api 호출에 문제 있는지 확인(api 디렉토리가 아닌, utils 디렉토리 내의 함수 가져와서 호출해보기)
- [ ] search 페이지 fetch된 data 없으면, 에러 페이지가 뜸. 에러처리 할 수 있는 조건문 필요
- [ ] 에러페이지 생성

## 교훈
- vercel preview를 꼭 확인하자

**Comment by dlsxody1** [comment]
지금 ec2에서 https를 연결하기 위해서 도메인 하나 플렉스 해버렸습니다 (550원...)
해결되면 다시 알려드릴게요...!!!!!
