### ISSUE TITLE
[search] 저장된 경로를 눌렀을 때 어디로 보내야 할지 의문입니다!

### ISSUE THREAD

**Issue by dlsxody1** [makchamakers/makchata#91]
## 질문 있습니다!
#90 
저장된 경로를 클릭했을 때 어느 페이지로 보내야 자연스러울까? 라는 생각이 들었습니다.
이 생각이 들었던 이유는 저희는 index를 통해서 route/1...2...3 이런식으로 페이지를 만들고 있잖아요?
그렇다 보니 

![image](https://github.com/makchamakers/makchata/assets/62875596/4169d64a-ada9-422a-b7e7-299d1cd5056d)

위의 정보를 통해서 바로 route 페이지로 보낼 수 없고search 결과 페이지로 이동해야 합니다
물론 유저가 상황에 따라 이동수단을 변하게 할 수 있다고 생각하지만 
route 페이지를 보고 싶어 할 수도 있다 라고 생각이 들어서
어떻게 해야 자연스러운 페이지 이동인지 고민이 되어서 여쭤봅니다...!!!
전에 입력했던 경로를 눌렀을 때 어디로가야 자연스러울까요?! 1번 ? 2번?

## 1번
![image](https://github.com/makchamakers/makchata/assets/62875596/4e82f478-4b8d-4d73-a5e5-b7ced1cd4d45)

##  2번
![image](https://github.com/makchamakers/makchata/assets/62875596/9bfc8784-9996-4bd8-bdd6-65b33d74fcc0)

<br />

++ 추가적으로 처음에 route api 만들 때 왜 녕녕이 왜 uuid 말씀하셨었는지 이해가 이제 가네요...ㅋㅋㅋㅋㅋㅋ ㅠㅠㅠ

**Comment by eun0leee** [comment]
@dlsxody1 

유저플로우에 대한 고민이라고 이해했습니다!
그렇다면 저장된 경로를 선택한다는게 플로우 중 어떤건지 이해가 되지 않는데, 자세히 설명해주실 수 있을까요?

현재는 `출발지 검색과 장소 선택, 도착지 검색과 장소 선택` -> `검색결과에서 이동경로 선택` -> `route페이지 이동`인데
알람이 설정된 후를 말하는걸까요?

**Comment by dlsxody1** [comment]
아뇨! 제가 말씀을 잘못드렸네요..! 저장된 경로 말고 최근 검색 경로라고 말씀드렸어야 할텐데..
아래 사진을 말씀드렸습니다!
![image](https://github.com/makchamakers/makchata/assets/62875596/0f3fe95a-f45c-40ce-8fe0-537c520a04ee)

근데 이제 와서 생각해보니까 출발지와 목적지가 있으니까 2번으로 가는게 맞는 것처럼 보이네요..?!

**Comment by eun0leee** [comment]
@dlsxody1 

그러네요! 2번으로 가서 이동경로를 보면 되지 않을까 싶습니다😀

**Comment by dlsxody1** [comment]
같이 고민해주셔서 감사합니다!!!
